### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by happysurf** [y4v8/helper_google_translate#1]
Doesn't work on 52beta, nothing happen.

**Comment by y4v8** [comment]
Short press (less than 500 ms) on the CTRL key.
I tested on Firefox 51.0.1 / 53.0a2 and Chrome 56.0.

**Comment by happysurf** [comment]
OK now works also for me.
The idea is good but unfortunately doesn't works in text area.
I s possible add this feature?
Thanks.
EDIT: I have changed my rating on AMO.

**Comment by y4v8** [comment]
Added handling for textarea in v.2.0.3

>>If you maintain a legacy add-on, such as a XUL overlay, bootstrapped, or Add-on SDK-based add-on, we recommend that you investigate porting it to WebExtensions.
https://developer.mozilla.org/en-US/Add-ons

WebExtensions does not work on addons.mozilla.org (AMO), and Chrome extensions does not work on chrome.google.com. Probably this is done for security reasons.

**Comment by happysurf** [comment]
Thank you for the info, translation in text area works fine in v.2.0.3.

**Comment by y4v8** [comment]
Added in v2.1.1. By default the menu is not shown, turn on in settings.

**Comment by y4v8** [comment]
Versions 2.1.* were rejected without any comment.

**Comment by happysurf** [comment]
Therefore is impossible add the "Translate the page" feature in Firefox Web Extensions API ?

**Comment by y4v8** [comment]
After a short press of the Ctrl key, you switch to the window(tab) of Google Translate.
If the selected text exists and the window(tab) of Google Translate already exists, the text is copied into Google Translate.
If a window(tab) with Google Translate is not found, just a new tab is opened.

When you press Ctrl on the Google Translate page, you return to the previous page.

* The duration of a short press of up to 250 milliseconds, that made for case you want to press a combination, for example Ctrl+S, but after having pressed Ctrl you changed your intentions.
* The tab of Google Translate move behind the current tab.
* Working with a private window is more convenient - the actions do not put into the history and the window can be placed on the second monitor.
* For convenience, after switching to the Google Translate, the focus moves to the editable area.

**Comment by y4v8** [comment]
The extension does not work on the following sites - addons.mozilla.org (for security reasons), docs.google.com (there is no possibility to get the selected text) and others, similar to docs.google.com.

**Comment by y4v8** [comment]
>>Therefore is impossible add the "Translate the page" feature in Firefox Web Extensions API ?
I used in version ![2.1.2](https://github.com/y4v8/helper_google_translate/releases/tag/v2.1.2) an external script 'translate_a/element.js' from the site translate.google.com. But this is not allowed:
>>We don't allow add-ons to use remote scripts because they can create serious security vulnerabilities.
